config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/welcome'
  get 'pages/dashboard'
  get 'pages/home'

  get '/presupuestos', to: 'budgets#index', as: 'presupuestos'

  resources :budet_details
  resources :budgets
  resources :products
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
end

app/models/budet_detail.rb
class BudetDetail < ApplicationRecord
  belongs_to :budget
  has_many :product
end

app/controllers/budet_details_controller.rb
class BudetDetailsController < ApplicationController
  before_action :set_budet_detail, only: [:show, :edit, :update, :destroy]

  # GET /budet_details
  # GET /budet_details.json
  def index
    @budet_details = BudetDetail.all
  end

  # GET /budet_details/1
  # GET /budet_details/1.json
  def show
  end

  # GET /budet_details/new
  def new
    @budet_detail = BudetDetail.new
  end

  # GET /budet_details/1/edit
  def edit
  end

  # POST /budet_details
  # POST /budet_details.json
  def create
    @budet_detail = BudetDetail.new(budet_detail_params)

    respond_to do |format|
      if @budet_detail.save
        format.html { redirect_to @budet_detail, notice: 'Budet detail was successfully created.' }
        format.json { render :show, status: :created, location: @budet_detail }
      else
        format.html { render :new }
        format.json { render json: @budet_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budet_details/1
  # PATCH/PUT /budet_details/1.json
  def update
    respond_to do |format|
      if @budet_detail.update(budet_detail_params)
        format.html { redirect_to @budet_detail, notice: 'Budet detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @budet_detail }
      else
        format.html { render :edit }
        format.json { render json: @budet_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budet_details/1
  # DELETE /budet_details/1.json
  def destroy
    @budet_detail.destroy
    respond_to do |format|
      format.html { redirect_to budet_details_url, notice: 'Budet detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budet_detail
      @budet_detail = BudetDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budet_detail_params
      params.require(:budet_detail).permit(:budget_id, :product_id, :amount, :unit_price, :subtotal)
    end
end

app/helpers/budet_details_helper.rb
module BudetDetailsHelper
end

app/views/budet_details/_form.html.erb
<%= form_with(model: budet_detail, local: true) do |form| %>
  <% if budet_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budet_detail.errors.count, "error") %> prohibited this budet_detail from being saved:</h2>

      <ul>
      <% budet_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :budget_id %>
    <%= form.text_field :budget_id %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :unit_price %>
    <%= form.text_field :unit_price %>
  </div>

  <div class="field">
    <%= form.label :subtotal %>
    <%= form.text_field :subtotal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/budet_details/edit.html.erb
<h1>Editing Budet Detail</h1>

<%= render 'form', budet_detail: @budet_detail %>

<%= link_to 'Show', @budet_detail %> |
<%= link_to 'Back', budet_details_path %>

app/views/budet_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Budet Details</h1>

<table>
  <thead>
    <tr>
      <th>Budget</th>
      <th>Product</th>
      <th>Amount</th>
      <th>Unit price</th>
      <th>Subtotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budet_details.each do |budet_detail| %>
      <tr>
        <td><%= budet_detail.budget %></td>
        <td><%= budet_detail.product %></td>
        <td><%= budet_detail.amount %></td>
        <td><%= budet_detail.unit_price %></td>
        <td><%= budet_detail.subtotal %></td>
        <td><%= link_to 'Show', budet_detail %></td>
        <td><%= link_to 'Edit', edit_budet_detail_path(budet_detail) %></td>
        <td><%= link_to 'Destroy', budet_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budet Detail', new_budet_detail_path %>

app/views/budet_details/new.html.erb
<h1>New Budet Detail</h1>

<%= render 'form', budet_detail: @budet_detail %>

<%= link_to 'Back', budet_details_path %>

app/views/budet_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Budget:</strong>
  <%= @budet_detail.budget %>
</p>

<p>
  <strong>Product:</strong>
  <%= @budet_detail.product %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @budet_detail.amount %>
</p>

<p>
  <strong>Unit price:</strong>
  <%= @budet_detail.unit_price %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @budet_detail.subtotal %>
</p>

<%= link_to 'Edit', edit_budet_detail_path(@budet_detail) %> |
<%= link_to 'Back', budet_details_path %>