config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'pages/welcome'
  get 'pages/dashboard'
  get 'pages/home'

  get '/presupuestos', to: 'budgets#index', as: 'presupuestos'

  resources :budet_details
  resources :budgets
  resources :products
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "pages#home"
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :customer
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:customer_id, :title, :description, :start_date, :end_date)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with(model: budget, local: true) do |form| %>
  <% if budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, class: "form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, class: "form-control custom-select" %>
  </div>

  <div class="actions">
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Presupuestos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Customer</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Start date</th>
      <th scope="col">End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <th scope="row"><%= budget.id %></th>
        <td><%= budget.customer.business_name %></td>
        <td><%= budget.title %></td>
        <td><%= budget.description %></td>
        <td><%= budget.start_date %></td>
        <td><%= budget.end_date %></td>
        <td><%= link_to "<i class=\"far fa-eye\"></i>".html_safe, budget, class: "btn btn-sm" %></td>
        <td><%= link_to "<i class=\"far fa-edit\"></i>".html_safe, edit_budget_path(budget), class: "btn btn-sm" %></td>
        <td><%= link_to "<i class=\"fas fa-trash\"></i>".html_safe, budget, method: :delete, data: { confirm: '¿Esta seguro que desea eliminar este recurso?' }, class: "btn btn-sm alert-danger" -%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<%= link_to "<i class=\"fas fa-plus\"></i> Nuevo presupuesto".html_safe, new_budget_path, class: "btn btn-primary btn-sm" %>
<br>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form', budget: @budget %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @budget.customer %>
</p>

<p>
  <strong>Title:</strong>
  <%= @budget.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @budget.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @budget.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @budget.end_date %>
</p>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>